name: Learning Path 2

on:
  push:
    branches:
      - publish-latest-learning-path

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "temp-main"
        github_token: ${{ secrets.GITHUB_TOKEN }}